override: false

scheme: Gemini

menu:
  home: / || fa fa-home
  课程时间及讲义: /slides/ || fa fa-book
  实验时间及讲义: /experiment/ || fa fa-book
  课程作业: /homework/ || fa fa-book
  快船总冠军: /homework/ || fa fa-book

toc:
  expand_all: true
